# Generated by Django 3.2.25 on 2025-06-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_data', models.JSONField()),
                ('fetch_date', models.JSONField(null=True)),
                ('time_range_start', models.JSONField(null=True)),
                ('time_range_end', models.JSONField(null=True)),
                ('coffee_commodity_price_fluctuation', models.JSONField(default=list)),
                ('coffee_geopolitical_tensions', models.JSONField(default=list)),
                ('coffee_logistics_delays', models.JSONField(default=list)),
                ('coffee_shipping_costs', models.JSONField(default=list)),
                ('coffee_freight_rates', models.JSONField(default=list)),
                ('coffee_natural_disasters', models.JSONField(default=list)),
                ('coffee_labor_strikes', models.JSONField(default=list)),
                ('coffee_market_shortage', models.JSONField(default=list)),
                ('coffee_procurement_fraud', models.JSONField(default=list)),
                ('coffee_supplier_risk', models.JSONField(default=list)),
                ('coffee_global_demand_shift', models.JSONField(default=list)),
                ('coffee_manufacturing_slowdown', models.JSONField(default=list)),
                ('coffee_regulatory_changes', models.JSONField(default=list)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.commodity')),
            ],
        ),
        migrations.AddIndex(
            model_name='commoditynews',
            index=models.Index(fields=['commodity'], name='procurement_commodi_8f8a7f_idx'),
        ),
    ]
