# Generated by Django 3.2.25 on 2025-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_auto_20250621_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementNewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='procurementnewssummary',
            index=models.Index(fields=['created_at'], name='procurement_created_6c248e_idx'),
        ),
    ]
